In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv(r"D:\Internship\Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.shape

(891, 12)

In [16]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [22]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [23]:
(df.isnull().sum() / len(df)) * 100

#tells the percentage of missing data in each column.

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [24]:
df['Sex'].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [25]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [26]:
df['Pclass'].unique()

array([3, 1, 2])

In [28]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [29]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [30]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [31]:
df['Age'].isnull().sum()

np.int64(0)

In [32]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [33]:
df['Embarked'].isnull().sum()

np.int64(0)

In [34]:
df['Cabin'].isnull().sum()

np.int64(687)

In [35]:
(df['Cabin'].isnull().sum() / len(df)) * 100

np.float64(77.10437710437711)

In [36]:
df['Cabin'].dropna().head(20)

1             C85
3            C123
6             E46
10             G6
11           C103
21            D56
23             A6
27    C23 C25 C27
31            B78
52            D33
54            B30
55            C52
61            B28
62            C83
66            F33
75          F G73
88    C23 C25 C27
92            E31
96             A5
97        D10 D12
Name: Cabin, dtype: str

In [37]:
df = df.drop(columns = ['Cabin'])

In [38]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

In [39]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Embarked           str
dtype: object

In [40]:
df.select_dtypes(include=np.number).columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='str')

In [41]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.361582,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.019697,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [42]:
numerical_columns = ['Age', 'Fare']

for column in numerical_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    print(f"{column}:")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")
    print(f"Number of Outliers: {len(outliers)}")
    print()

Age:
Lower Bound: 2.5
Upper Bound: 54.5
Number of Outliers: 66

Fare:
Lower Bound: -26.724
Upper Bound: 65.6344
Number of Outliers: 116

In [43]:
age_outliers = df[(df['Age'] < 2.5) | (df['Age'] > 54.5)]

age_outliers['Age'].sort_values()

803     0.42
755     0.67
644     0.75
469     0.75
78      0.83
       ...
116    70.50
493    71.00
96     71.00
851    74.00
630    80.00
Name: Age, Length: 66, dtype: float64

In [44]:
fare_outliers = df[df['Fare'] > 65.6344]

fare_outliers['Fare'].sort_values()

151     66.6000
336     66.6000
369     69.3000
641     69.3000
201     69.5500
         ...
341    263.0000
438    263.0000
258    512.3292
679    512.3292
737    512.3292
Name: Fare, Length: 116, dtype: float64

Outliers were detected using the IQR method. The identified observations were inspected and found to represent plausible passenger ages and legitimate fare values. Therefore, they were retained rather than removed, avoiding unnecessary loss of valid information.

In [45]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

In [46]:
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [47]:
df.head

<bound method NDFrame.head of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name   Age  SibSp  Parch  \
0                              Braund, Mr. Owen Harris  22.0      1      0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0
2                               Heikkinen, Miss. Laina  26.0      0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0
4                             Allen, Mr. William Henry  35.0      0      0
..                                                 ...   ...    ...    ...
886                              Montvila, Rev. Juozas  27.0      0      0
887                       Graham, Miss. Margaret Edith  19.0      0      0
888           Johnston, Miss. Catherine Helen "Carrie"  28.0      1      2
889                              Behr, Mr. Karl Howell  26.0      0      0
890                                Dooley, Mr. Patrick  32.0      0      0

               Ticket     Fare  Sex_male  Embarked_Q  Embarked_S
0           A/5 21171   7.2500      True       False        True
1            PC 17599  71.2833     False       False       False
2    STON/O2. 3101282   7.9250     False       False        True
3              113803  53.1000     False       False        True
4              373450   8.0500      True       False        True
..                ...      ...       ...         ...         ...
886            211536  13.0000      True       False        True
887            112053  30.0000     False       False        True
888        W./C. 6607  23.4500     False       False        True
889            111369  30.0000      True       False       False
890            370376   7.7500      True        True       False

[891 rows x 12 columns]>

In [48]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Sex_male          bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [49]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Sex_male       0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Sex_male     891 non-null    bool
 10  Embarked_Q   891 non-null    bool
 11  Embarked_S   891 non-null    bool
dtypes: bool(3), float64(2), int64(5), str(2)
memory usage: 65.4 KB

In [52]:
df.shape

(891, 12)

In [53]:
df.to_csv('Titanic_Cleaned.csv', index=False)